#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '2'

services:

  ca0.example.com:
    extends:
        file: docker-compose-base.yaml
        service: ca0
    container_name: ca0.example.com

  ca1.example.com:
    extends:
        file: docker-compose-base.yaml
        service: ca1
    container_name: ca1.example.com

  orderer.example.com:
    extends:
        file: docker-compose-base.yaml
        service: orderer
    container_name: orderer.example.com

  peer0.bank-of-dinero.com:
    extends:
        file: docker-compose-base.yaml
        service: peer
    container_name: peer0.bank-of-dinero.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.bank-of-dinero.com
      - CORE_PEER_ADDRESS=peer0.bank-of-dinero.com:7051
      - CORE_PEER_LISTENADDRESS=peer0.bank-of-dinero.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.bank-of-dinero.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank-of-dinero.com:7051
      - CORE_PEER_LOCALMSPID=BankOfDineroMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.bank-of-dinero.com:5984

    ports:
      - 7051:7051
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-material/crypto-config/peerOrganizations/bank-of-dinero.com/peers/peer0.bank-of-dinero.com/:/etc/hyperledger/peer
    depends_on:
      - orderer.example.com
      - couchdb.bank-of-dinero.com

  couchdb.bank-of-dinero.com:
    extends:
        file: docker-compose-base.yaml
        service: couchdb
    container_name: couchdb.bank-of-dinero.com
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  peer0.eastwood-banking.com:
    extends:
        file: docker-compose-base.yaml
        service: peer
    container_name: peer0.eastwood-banking.com

    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.eastwood-banking.com
      - CORE_PEER_ADDRESS=peer0.eastwood-banking.com:8051
      - CORE_PEER_LISTENADDRESS=peer0.eastwood-banking.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.eastwood-banking.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.eastwood-banking.com:8051
      - CORE_PEER_LOCALMSPID=EastwoodBankingMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.eastwood-banking.com:5984
    ports:
      - 8051:8051
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-material/crypto-config/peerOrganizations/eastwood-banking.com/peers/peer0.eastwood-banking.com:/etc/hyperledger/peer
    depends_on:
      - orderer.example.com
      - couchdb.eastwood-banking.com

  couchdb.eastwood-banking.com:
    extends:
        file: docker-compose-base.yaml
        service: couchdb
    container_name: couchdb.eastwood-banking.com
    ports:
      - 6984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  bankofdinero_cli:
    extends:
      file: docker-compose-base.yaml
      service: clibase
    container_name: bankofdinero_cli

    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bank-of-dinero.com:7051
      - CORE_PEER_LOCALMSPID=BankOfDineroMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/config/crypto-config/peerOrganizations/bank-of-dinero.com/users/Admin@bank-of-dinero.com/msp
    volumes:
      - /var/run/:/host/var/run/
    depends_on:
      - peer0.bank-of-dinero.com
      
  eastwoodbanking_cli:
    extends:
      file: docker-compose-base.yaml
      service: clibase
    container_name: eastwoodbanking_cli

    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.eastwood-banking.com:8051
      - CORE_PEER_LOCALMSPID=EastwoodBankingMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/config/crypto-config/peerOrganizations/eastwood-banking.com/users/Admin@eastwood-banking.com/msp
    volumes:
      - /var/run/:/host/var/run/
    depends_on:
      - peer0.eastwood-banking.com